version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: home-app-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: homeapp
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - home-app-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: home-app-backend
    restart: unless-stopped
    network_mode: host
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@localhost:27017/homeapp?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      OLLAMA_BASE_URL: http://100.104.68.115:11434
      OLLAMA_MODEL: hf.co/unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF:Q8_K_XL
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Next.js App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: home-app-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - home-app-network

  # Redis for session management (optional for future scaling)
  redis:
    image: redis:7.0-alpine
    container_name: home-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - home-app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  home-app-network:
    driver: bridge